### ISSUE TITLE
Error unable to build Hibernate SessionFactory

### ISSUE THREAD

**Issue by danmarrod** [danmarrod/TFG1617-Caesar#26]
When you set a domain attribute of type Map, the next message on deployment is show:

Caused by: org.hibernate.MappingException: Could not determine type for: java.util.Map, at table: test, for columns: [org.hibernate.mapping.Column(responses)]
	at org.hibernate.mapping.SimpleValue.getType(SimpleValue.java:431) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.mapping.SimpleValue.isValid(SimpleValue.java:398) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.mapping.Property.isValid(Property.java:225) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.mapping.PersistentClass.validate(PersistentClass.java:595) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.mapping.UnionSubclass.validate(UnionSubclass.java:44) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:329) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:443) ~[hibernate-core-5.0.12.Final.jar:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879) ~[hibernate-entitymanager-5.0.12.Final.jar:5.0.12.Final]
	... 22 common frames omitted

**Comment by danmarrod** [comment]
A Map type must be included @ElementCollection annotation:
	
@ElementCollection
	public Map<Integer, Question> getResponses() {
		return responses;
	}
